In [1]:
import gym
env = gym.make('MountainCar-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

KeyboardInterrupt: 

In [3]:
import gym
env = gym.make('CartPole-v0')

In [6]:
env.action_space

Discrete(2)

In [13]:
gym.Space

gym.spaces.space.Space

In [18]:
import numpy as np
from gym import spaces as S
b = S.Box(low=-np.inf, high=np.inf, shape=(12,))
b.sample()[4]

-0.05641373

In [15]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

2021-07-31 17:23:25.315 Python[2323:58394] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/7h/6jgdtfq939gc0fkr1959w_3w0000gn/T/org.python.python.savedState


[ 0.03117583 -0.03388213 -0.02941372 -0.01123784]
{}
[ 0.03049819  0.16164904 -0.02963848 -0.31305411]
{}
[ 0.03373117 -0.03303843 -0.03589956 -0.02986361]
{}
[ 0.0330704   0.16257946 -0.03649684 -0.33365359]
{}
[ 0.03632199  0.35820135 -0.04316991 -0.6376187 ]
{}
[ 0.04348602  0.55389786 -0.05592228 -0.94357799]
{}
[ 0.05456397  0.74972684 -0.07479384 -1.25329484]
{}
[ 0.06955851  0.94572286 -0.09985974 -1.56843583]
{}
[ 0.08847297  0.75192521 -0.13122846 -1.30849756]
{}
[ 0.10351147  0.55868726 -0.15739841 -1.05960338]
{}
[ 0.11468522  0.36596032 -0.17859047 -0.82017089]
{}
[ 0.12200442  0.17367292 -0.19499389 -0.5885542 ]
{}
[ 0.12547788 -0.0182611  -0.20676498 -0.36307481]
{}
Episode finished after 13 timesteps
[-0.00475669 -0.01684158  0.04230506  0.01733698]
{}
[-0.00509352 -0.2125439   0.0426518   0.32306179]
{}
[-0.0093444  -0.40824642  0.04911304  0.62888443]
{}
[-0.01750933 -0.21384303  0.06169073  0.35206439]
{}
[-0.02178619 -0.01965012  0.06873202  0.07945471]
{}
[-0.022179

[-0.09258911 -0.75155884  0.17105158  1.36378792]
{}
[-0.10762028 -0.55894194  0.19832734  1.12912334]
{}
Episode finished after 12 timesteps
[-0.0205062  -0.04807711  0.00042187  0.0119201 ]
{}
[-0.02146774 -0.24320511  0.00066028  0.3047361 ]
{}
[-0.02633184 -0.04809257  0.006755    0.01226148]
{}
[-0.0272937   0.14693185  0.00700023 -0.27828253]
{}
[-0.02435506  0.34195324  0.00143458 -0.5687494 ]
{}
[-0.01751599  0.53705505 -0.00994041 -0.86098003]
{}
[-0.00677489  0.34206987 -0.02716001 -0.57143915]
{}
[ 6.65049232e-05  1.47339094e-01 -3.85887946e-02 -2.87434778e-01]
{}
[ 0.00301329  0.3429895  -0.04433749 -0.5920342 ]
{}
[ 0.00987308  0.14851538 -0.05617817 -0.31364064]
{}
[ 0.01284338  0.34439074 -0.06245099 -0.62349787]
{}
[ 0.0197312   0.15019378 -0.07492094 -0.35111894]
{}
[ 0.02273507  0.34629679 -0.08194332 -0.66645444]
{}
[ 0.02966101  0.15240435 -0.09527241 -0.40065607]
{}
[ 0.0327091   0.3487395  -0.10328553 -0.72179096]
{}
[ 0.03968389  0.54512705 -0.11772135 -1.0451143

In [7]:
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer